-- seed.sql
INSERT OR IGNORE INTO manga (id, title, author, genres, status, total_chapters, description) VALUES 
('one-piece', 'One Piece', 'Eiichiro Oda', 'Action, Adventure', 'Ongoing', 1100, 'Epic pirate adventure.'),
('naruto', 'Naruto', 'Masashi Kishimoto', 'Action, Ninja', 'Completed', 700, 'A ninja seeks recognition.'),
('bleach', 'Bleach', 'Tite Kubo', 'Action, Supernatural', 'Completed', 686, 'Substitute Soul Reaper.'),
('death-note', 'Death Note', 'Tsugumi Ohba', 'Mystery, Thriller', 'Completed', 108, 'The killer notebook.'),
('attack-on-titan', 'Attack on Titan', 'Hajime Isayama', 'Action, Drama', 'Completed', 139, 'Walls vs Titans.'),
('demon-slayer', 'Demon Slayer', 'Koyoharu Gotouge', 'Action, Fantasy', 'Completed', 205, 'Sword vs Demons.'),
('jujutsu-kaisen', 'Jujutsu Kaisen', 'Gege Akutami', 'Action, Horror', 'Ongoing', 250, 'Sorcerers vs Curses.'),
('chainsaw-man', 'Chainsaw Man', 'Tatsuki Fujimoto', 'Action, Gore', 'Ongoing', 160, 'Devil hunter heart.'),
('spy-x-family', 'Spy x Family', 'Tatsuya Endo', 'Comedy, Action', 'Ongoing', 95, 'A fake family secret.'),
('blue-lock', 'Blue Lock', 'Muneyuki Kaneshiro', 'Sports', 'Ongoing', 250, 'Survival soccer.'),
('vinland-saga', 'Vinland Saga', 'Makoto Yukimura', 'History, Action', 'Ongoing', 200, 'Viking revenge.'),
('berserk', 'Berserk', 'Kentaro Miura', 'Dark Fantasy', 'Ongoing', 375, 'The Black Swordsman.'),
('monster', 'Monster', 'Naoki Urasawa', 'Thriller, Seinen', 'Completed', 162, 'Psychological chase.'),
('fullmetal-alchemist', 'Fullmetal Alchemist', 'Hiromu Arakawa', 'Adventure, Alchemy', 'Completed', 108, 'The Elric brothers.'),
('vagabond', 'Vagabond', 'Takehiko Inoue', 'History, Martial Arts', 'Ongoing', 327, 'Samurai path.'),
('slam-dunk', 'Slam Dunk', 'Takehiko Inoue', 'Sports', 'Completed', 276, 'Basketball legacy.'),
('haikyuu', 'Haikyuu!!', 'Haruichi Furudate', 'Sports', 'Completed', 402, 'Volleyball grit.'),
('tokyo-ghoul', 'Tokyo Ghoul', 'Sui Ishida', 'Horror, Tragedy', 'Completed', 143, 'Half-ghoul struggle.'),
('one-punch-man', 'One Punch Man', 'ONE', 'Comedy, Action', 'Ongoing', 200, 'Bored super-hero.'),
('hunter-x-hunter', 'Hunter x Hunter', 'Yoshihiro Togashi', 'Adventure', 'Ongoing', 400, 'Finding Dad.'),
('dragon-ball', 'Dragon Ball', 'Akira Toriyama', 'Action', 'Completed', 519, 'Z-warriors.'),
('jojo-adventure', 'JoJo Bizarre Adventure', 'Hirohiko Araki', 'Action, Fantasy', 'Ongoing', 900, 'Family destiny.'),
('black-clover', 'Black Clover', 'Yuki Tabata', 'Fantasy, Magic', 'Ongoing', 370, 'Magicless wizard.'),
('fairy-tail', 'Fairy Tail', 'Hiro Mashima', 'Fantasy', 'Completed', 545, 'Mage guild bonds.'),
('dr-stone', 'Dr. Stone', 'Riichiro Inagaki', 'Sci-Fi, Adventure', 'Completed', 232, 'Kingdom of Science.'),
('fire-force', 'Fire Force', 'Atsushi Ohkubo', 'Sci-Fi, Action', 'Completed', 304, 'Fiery firefighters.'),
('tokyo-revengers', 'Tokyo Revengers', 'Ken Wakui', 'Action', 'Completed', 278, 'Time-leap delinquent.'),
('blue-exorcist', 'Blue Exorcist', 'Kazue Kato', 'Supernatural', 'Ongoing', 150, 'Satans exorcist son.'),
('solo-leveling', 'Solo Leveling', 'Chu-Gong', 'Action, Fantasy', 'Completed', 179, 'Weakest to strongest.'),
('kingdom', 'Kingdom', 'Yasuhisa Hara', 'History, War', 'Ongoing', 780, 'Ancient China war.'),
('gintama', 'Gintama', 'Hideaki Sorachi', 'Comedy, Samurai', 'Completed', 704, 'Odd jobs in Edo.'),
('kaguya-sama', 'Kaguya-sama', 'Aka Akasaka', 'Romance, Comedy', 'Completed', 281, 'Love is war.'),
('horimiya', 'Horimiya', 'HERO', 'Romance, School', 'Completed', 125, 'High school secrets.'),
('nana', 'Nana', 'Ai Yazawa', 'Drama, Music', 'Ongoing', 84, 'Two Nanas.'),
('my-hero-academia', 'My Hero Academia', 'Kohei Horikoshi', 'Action, School', 'Ongoing', 420, 'Hero society.');